# Generated by Django 2.1.3 on 2019-03-12 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file_name', models.CharField(max_length=100, verbose_name='Name')),
                ('backup_file_size', models.CharField(max_length=100, verbose_name='Size')),
                ('backup_file_created_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Created at')),
                ('backup_file_updated_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Access_Permissions',
            fields=[
                ('access_permission_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Access Permission Name')),
                ('access_permission_details', models.CharField(blank=True, max_length=255, verbose_name='Details')),
                ('access_permission_created_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Created at')),
                ('access_permission_updated_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Failed_Login',
            fields=[
                ('failed_login_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('failed_login_username', models.CharField(max_length=255, verbose_name='Username')),
                ('failed_login_password', models.CharField(max_length=255, verbose_name='Password')),
                ('failed_login_from', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend')], default='frontend', max_length=10, verbose_name='From')),
                ('failed_login_ip_address', models.CharField(max_length=100, verbose_name='Ip Address')),
                ('failed_login_attempted_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
                ('failed_login_status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Operator_Access_Permissions',
            fields=[
                ('operator_access_permission_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('operator_access_permission_updated_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
                ('operator_access_permission_updated_by', models.EmailField(blank=True, max_length=255, verbose_name='Updated by')),
                ('access_permissions_access_permission_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Access_Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Operator_Logs',
            fields=[
                ('operator_log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Log Id')),
                ('operators_operator_id', models.IntegerField(default=0, verbose_name='Operator Id')),
                ('operators_operator_username', models.CharField(max_length=100, verbose_name='Username')),
                ('operators_operator_name', models.CharField(max_length=100, verbose_name='Name')),
                ('operator_log_message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('operator_log_browser', models.TextField(blank=True, verbose_name='Browser')),
                ('operator_log_ip_address', models.CharField(blank=True, max_length=30, verbose_name='Ip address')),
                ('operator_log_updated_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
                ('operator_log_updated_by', models.EmailField(blank=True, max_length=255, verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Operator Id')),
                ('operator_type', models.CharField(choices=[('', '--select--'), ('super-admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('office-owner', 'Office Owner'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('operator_username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('operator_auth_key', models.CharField(max_length=255, verbose_name='Auth key')),
                ('operator_password_hash', models.CharField(max_length=255, verbose_name='Password')),
                ('operator_password_reset_token', models.CharField(blank=True, max_length=255, verbose_name='Password reset token')),
                ('operator_name', models.CharField(max_length=100, verbose_name='Name')),
                ('operator_gender', models.CharField(choices=[('', '--select--'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=6, verbose_name='Gender')),
                ('operator_contact_phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+250123456789'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)], verbose_name='Phone Number')),
                ('operator_contact_email_id', models.EmailField(blank=True, max_length=100, verbose_name='Email id')),
                ('operator_profile_photo_file_path', models.CharField(blank=True, max_length=255, verbose_name='Profile photo file path')),
                ('operator_created_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Created by')),
                ('operator_created_by', models.EmailField(blank=True, max_length=255, verbose_name='Created by')),
                ('operator_updated_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated at')),
                ('operator_updated_by', models.EmailField(blank=True, max_length=255, verbose_name='Updated by')),
                ('operator_status', models.CharField(choices=[('', '--select--'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Unverified'), ('unverified', 'Unapproved'), ('unapproved', 'Blocked')], default='unverified', max_length=20, verbose_name='Status')),
            ],
        ),
        migrations.AddField(
            model_name='operator_access_permissions',
            name='operators_operator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Operators'),
        ),
    ]
