# Generated by Django 2.1.3 on 2019-03-15 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_order_approvals_order_attachments_order_items_order_logs_order_payments_order_proposals_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operators',
            name='operator_contact_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(
                message="Phone number must be entered in the format: '1-(555)-555-5555'. Up to 17 digits allowed.",
                regex='^\\+?1?\\d{9,17}$'), django.core.validators.MinLengthValidator(9),
                                                                          django.core.validators.MaxLengthValidator(
                                                                              17)], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='operators',
            name='operator_department',
            field=models.CharField(choices=[('', '--select--'), ('NONE', 'NONE'), ('DCOP', 'Deputy COP (Agriculture)'),
                                            ('BFM', 'Business, Finance & Marketing'), ('NUTRITION', 'Nutrition'),
                                            ('DAF', 'Administrative and Finance'), ('MAE', 'Monitoring and Evaluation'),
                                            ('GRANT-MANAGER', 'Grant Manager')], default='NONE', max_length=255,
                                   verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='operators',
            name='operator_role',
            field=models.CharField(
                choices=[('', '--select--'), ('NONE', 'NONE'), ('COP', 'COP'), ('OPM', 'OPM'), ('Director', 'Director'),
                         ('Adviser', 'Adviser'), ('Regional Manager', 'Regional Manager'),
                         ('District Manager', 'District Manager'), ('Field Officer', 'Field Officer'),
                         ('Procurement Officer', 'Procurement Officer'), ('HR Manager', 'HR Manager'),
                         ('Stock Admin', 'Stock Admin'), ('Accountant Manager', 'Accountant Manager'),
                         ('Accountant Officer', 'Accountant Officer')], default='NONE', max_length=255,
                verbose_name='Role'),
        ),
    ]
