# Generated by Django 2.1.3 on 2019-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_auto_20190315_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                (
                'notification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Notification Id')),
                ('notification_from_type', models.CharField(
                    choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'), ('operator', 'Operator')],
                    default='system', max_length=20, verbose_name='Type')),
                ('notification_from_id', models.IntegerField(default=0, max_length=100, verbose_name='From Id')),
                ('notification_to_type', models.CharField(
                    choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'), ('operator', 'Operator')],
                    default='system', max_length=20, verbose_name='Type')),
                ('notification_to_id', models.IntegerField(default=0, max_length=100, verbose_name='To Id')),
                ('notification_message', models.CharField(max_length=255, verbose_name='Message')),
                ('notification_url', models.CharField(max_length=255, verbose_name='URL')),
                ('notification_created_at',
                 models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Created at')),
                ('notification_read_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Read at')),
                ('notification_fixed_at', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Fixed at')),
                ('notification_status', models.CharField(
                    choices=[('', '--select--'), ('unread', 'Unread'), ('read', 'Read'), ('fixed', 'Fixed')],
                    default='unread', max_length=20, verbose_name='Status')),
            ],
        ),
    ]
