# Generated by Django 2.1.3 on 2019-03-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0006_auto_20190316_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_requested_at',
            field=models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Requested At'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_requested_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_requested_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requested ID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_requested_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requested Title'),
        ),
    ]
