# Generated by Django 2.1.3 on 2019-03-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_auto_20190318_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_currency',
            field=models.CharField(choices=[('', '--select--'), ('USD', 'USD'), ('RWF', 'RWF')], default='RWF',
                                   max_length=255, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_item_currency',
            field=models.CharField(choices=[('', '--select--'), ('USD', 'USD'), ('RWF', 'RWF')], default='RWF',
                                   max_length=255, verbose_name='Currency'),
        ),
    ]
