# Generated by Django 2.1.3 on 2019-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_auto_20190318_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Department'),
        ),
        migrations.AddField(
            model_name='order_attachments',
            name='order_attachment_file_uploaded_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Uploaded Department'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_item_created_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Department'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_item_received_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Received Department'),
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_item_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Department'),
        ),
        migrations.AddField(
            model_name='order_payments',
            name='order_payment_paid_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Paid Department'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_acknowledged_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acknowledged Department'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_approval_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Approval Updated Department'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_created_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Department'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_evaluated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Evaluated Department'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_approved_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Approved Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_assigned_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assigned Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_assigned_to_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assigned To By'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_assigned_to_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assigned To Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_assigned_to_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assigned To ID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_closed_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Closed Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_created_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_paid_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Paid Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_procurement_method_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Procurement Method Updated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_proposal_generated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order Proposal Generated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_proposal_requested_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order Proposal Requested Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_purchase_generated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Purchase Order Generated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_requested_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Requested Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_reviewed_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reviewed Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Department'),
        ),
        migrations.AlterField(
            model_name='operators',
            name='operator_department',
            field=models.CharField(choices=[('', '--select--'), ('NONE', 'NONE'), ('DCOP', 'Deputy COP'),
                                            ('BFM', 'Business, Finance & Marketing'), ('NUTRITION', 'Nutrition'),
                                            ('DAF', 'Administrative and Finance'), ('MAE', 'Monitoring and Evaluation'),
                                            ('GRANT-MANAGER', 'Grant Manager')], default='NONE', max_length=255,
                                   verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='order_approvals',
            name='order_approval_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
        migrations.AlterField(
            model_name='order_attachments',
            name='order_attachment_file_uploaded_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Uploaded Role'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_item_created_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Role'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_item_received_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Received Role'),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='order_item_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
        migrations.AlterField(
            model_name='order_payments',
            name='order_payment_paid_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Paid Role'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_acknowledged_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Acknowledged Role'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_approval_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Approval Updated Role'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_created_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Role'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_evaluated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Evaluated Role'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_approved_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Approved Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_assigned_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assigned Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_assigned_to_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assigned To Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_closed_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Closed Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_created_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_paid_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Paid Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_procurement_method_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Procurement Method Updated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_proposal_generated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order Proposal Generated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_proposal_requested_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order Proposal Requested Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_purchase_generated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Purchase Order Generated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_requested_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Requested Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_reviewed_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Reviewed Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
    ]
