# Generated by Django 2.1.3 on 2019-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0010_auto_20190318_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_model_id',
            field=models.IntegerField(default=0, verbose_name='Model Id'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_model_type',
            field=models.CharField(
                choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'), ('operator', 'Operator')],
                default='system', max_length=20, verbose_name='Type'),
        ),
    ]
