# Generated by Django 2.1.3 on 2019-03-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0012_auto_20190319_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_created_at',
            field=models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_created_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_created_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Created Department'),
        ),
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_created_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Created ID'),
        ),
        migrations.AddField(
            model_name='order_approvals',
            name='order_approval_created_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
    ]
