# Generated by Django 2.1.3 on 2019-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0014_auto_20190319_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationsTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Message')),
                ('datetime', models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Time')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='order_supplier_updated_at',
            field=models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Vendor Updated At'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_supplier_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor Updated By'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_supplier_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendor Updated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_supplier_updated_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vendor Updated ID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_supplier_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vendor Updated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_procurement_method',
            field=models.CharField(
                choices=[('', '--select--'), ('Single Sourcing', 'Single Sourcing'), ('Open Tender', 'Open Tender')],
                default='', max_length=255, verbose_name='Procurement Method'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('', '--select--'), ('pending', 'Pending'), ('requested', 'Requested'),
                                            ('level0-approved', 'Level0 Approved'),
                                            ('level1-approved', 'Level1 Approved'),
                                            ('level2-approved', 'Level2 Approved'),
                                            ('level3-approved', 'Level3 Approved'),
                                            ('level4-approved', 'Level4 Approved'),
                                            ('level5-approved', 'Level5 Approved'),
                                            ('level6-approved', 'Level6 Approved'),
                                            ('level1-rejected', 'Level1 Rejected'),
                                            ('level2-rejected', 'Level2 Rejected'),
                                            ('level3-rejected', 'Level3 Rejected'),
                                            ('level4-rejected', 'Level4 Rejected'),
                                            ('level5-rejected', 'Level5 Rejected'),
                                            ('level6-rejected', 'Level6 Rejected'), ('reviewed', 'Reviewed'),
                                            ('approved', 'Approved'), ('rejected', 'Rejected'),
                                            ('assigned', 'Assigned'), ('supplier-selected', 'Supplier Selected'),
                                            ('proposal-generated', 'Proposal Generated'),
                                            ('proposal-requested', 'Proposal Requested'),
                                            ('proposal-evaluated', 'Proposal Evaluated'),
                                            ('proposal-approved', 'Proposal Approved'),
                                            ('proposal-rejected', 'Proposal Rejected'),
                                            ('purchase-generated', 'Purchase Generated'),
                                            ('proposal-acknowledged', 'Proposal Acknowledged'),
                                            ('received', 'Received'), ('partially-paid', 'Partially Paid'),
                                            ('paid', 'Paid'), ('closed', 'Closed')], default='pending', max_length=255,
                                   verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_supplier_category',
            field=models.CharField(
                choices=[('', '--select--'), ('Category 1', 'Category 1'), ('Category 2', 'Category 2')], default='',
                max_length=255, verbose_name='Vendor Category'),
        ),
    ]
