# Generated by Django 2.1.3 on 2019-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0015_auto_20190322_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_message',
            field=models.TextField(default='', verbose_name='Email Message'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_proposal_submission_utl',
            field=models.CharField(default='', max_length=255, verbose_name='Proposal Submission URL'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_subject',
            field=models.CharField(default='', max_length=255, verbose_name='Email Subject'),
        ),
    ]
