# Generated by Django 2.1.3 on 2019-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0016_auto_20190323_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_email_to_supplier_proposal_submission_utl',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_proposal_submission_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proposal Submission URL'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_updated_at',
            field=models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_updated_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_updated_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Department'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_updated_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Updated ID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_email_to_supplier_updated_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Updated Role'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_email_to_supplier_message',
            field=models.TextField(blank=True, verbose_name='Email Message'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_email_to_supplier_subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='Email Subject'),
        ),
    ]
