# Generated by Django 2.1.3 on 2019-03-24 11:25

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0017_auto_20190324_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_email_to_supplier_message',
            field=tinymce.models.HTMLField(verbose_name='Email Message'),
        ),
    ]
