# Generated by Django 2.1.3 on 2019-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0018_auto_20190324_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_attachments',
            name='order_attachment_file_path',
            field=models.FileField(upload_to='attachments/', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='order_attachments',
            name='order_attachment_type_id',
            field=models.IntegerField(default=0, verbose_name='Type Id'),
        ),
    ]
