# Generated by Django 2.1.3 on 2019-03-26 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0020_auto_20190325_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_proposals',
            name='order_proposal_supplier_address',
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_av_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='AV No.'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_district',
            field=models.CharField(blank=True, max_length=255, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_plot_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='Plot No.'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_sector',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_bank_account_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_company_type',
            field=models.CharField(blank=True,
                                   choices=[('', '--select--'), ('company', 'Company'), ('association', 'Association'),
                                            ('individual', 'Individual')], default='', max_length=255,
                                   verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_legal_representatives',
            field=models.CharField(blank=True, max_length=255, verbose_name='Names of Legal Representatives'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference1_contact_email_id',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email id'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference1_contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(
                message="Phone number must be entered in the format: '+250123456789'. Up to 13 digits allowed.",
                regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10),
                                                                          django.core.validators.MaxLengthValidator(
                                                                              13)], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference1_contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference1_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference2_contact_email_id',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email id'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference2_contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(
                message="Phone number must be entered in the format: '+250123456789'. Up to 13 digits allowed.",
                regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10),
                                                                          django.core.validators.MaxLengthValidator(
                                                                              13)], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference2_contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference2_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference3_contact_email_id',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email id'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference3_contact_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(
                message="Phone number must be entered in the format: '+250123456789'. Up to 13 digits allowed.",
                regex='^\\+?1?\\d{9,15}$'), django.core.validators.MinLengthValidator(10),
                                                                          django.core.validators.MaxLengthValidator(
                                                                              13)], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference3_contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_previous_reference3_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bank Account Details'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_proposal_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tender Description Title'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_rf_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='RFQ/RFP/RFA'),
        ),
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_supplier_tin_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='TIN Number'),
        ),
        migrations.AlterField(
            model_name='order_attachments',
            name='order_attachment_type',
            field=models.CharField(choices=[('', '--select--'), ('order-email', 'Order Email'),
                                            ('order-proposal-business-license', 'Order Proposal Business License'),
                                            ('order-proposal-vat-registration', 'Order Proposal Vat Registration'),
                                            ('order-proposal-offer-letter', 'Order Proposal Offer Letter'),
                                            ('order-proposal-quotation', 'Order Proposal Quotation'),
                                            ('order-proposal-document', 'Order Proposal Document'),
                                            ('order-purchase', 'Order Purchase'), ('order-invoice', 'Order Invoice')],
                                   default='none', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_supplier_category',
            field=models.CharField(max_length=255, verbose_name='Vendor Category'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_supplier_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_supplier_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
