# Generated by Django 2.1.3 on 2019-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0021_auto_20190326_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_code',
            field=models.CharField(default=None, max_length=8, unique=True, verbose_name='Proposal Id'),
        ),
        migrations.AlterField(
            model_name='order_attachments',
            name='order_attachment_type',
            field=models.CharField(choices=[('', '--select--'), ('order-email', 'Order Email'),
                                            ('order-proposal-business-license', 'Order Proposal Business License'),
                                            ('order-proposal-vat-registration', 'Order Proposal Vat Registration'),
                                            ('order-proposal-offer-letter', 'Order Proposal Offer Letter'),
                                            ('order-proposal-quotation', 'Order Proposal Quotation'),
                                            ('order-proposal-reference-document', 'Order Proposal Reference Document'),
                                            ('order-proposal-other-document', 'Order Proposal Other Document'),
                                            ('order-purchase', 'Order Purchase'), ('order-invoice', 'Order Invoice')],
                                   default='none', max_length=255, verbose_name='Type'),
        ),
    ]
