# Generated by Django 2.1.3 on 2019-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0024_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('attachment_model', models.CharField(
                    choices=[('', '--select--'), ('none', 'None'), ('email', 'Email'), ('order', 'Order')],
                    default='none', max_length=255, verbose_name='Model')),
                ('attachment_model_id', models.IntegerField(default=0, verbose_name='Id')),
                ('attachment_type', models.CharField(
                    choices=[('', '--select--'), ('none', 'None'), ('email', 'Email'), ('order', 'Order')],
                    default='none', max_length=255, verbose_name='Type')),
                ('attachment_type_id', models.IntegerField(default=0, verbose_name='Id')),
                ('attachment_number', models.IntegerField(default=0, verbose_name='Number')),
                ('attachment_file_name', models.CharField(blank=True, max_length=255, verbose_name='File Name')),
                ('attachment_file_path', models.FileField(upload_to='attachments/', verbose_name='File Path')),
                ('attachment_file_size', models.CharField(blank=True, max_length=255, verbose_name='File Size')),
                ('attachment_file_type', models.CharField(blank=True, max_length=255, verbose_name='File Type')),
                ('attachment_file_uploaded_at',
                 models.DateTimeField(default='0001-01-01 00:00:00', verbose_name='Uploaded At')),
                ('attachment_file_uploaded_id',
                 models.CharField(blank=True, max_length=100, verbose_name='Uploaded ID')),
                ('attachment_file_uploaded_by',
                 models.CharField(blank=True, max_length=100, verbose_name='Uploaded By')),
                ('attachment_file_uploaded_department',
                 models.CharField(blank=True, max_length=255, verbose_name='Uploaded Department')),
                ('attachment_file_uploaded_role',
                 models.CharField(blank=True, max_length=255, verbose_name='Uploaded Role')),
            ],
        ),
    ]
