# Generated by Django 2.1.3 on 2019-03-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0025_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_proposals',
            name='order_proposal_cost_currency',
            field=models.CharField(choices=[('', '--select--'), ('USD', 'USD'), ('RWF', 'RWF')], default='RWF',
                                   max_length=255, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_from_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_model_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_to_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='order_proposals',
            name='order_proposal_evaluation_details',
            field=models.CharField(blank=True, max_length=255, verbose_name='Comments'),
        ),
    ]
