# Generated by Django 2.1.3 on 2019-03-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0031_auto_20190328_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='order_item_type_id',
            field=models.IntegerField(default=0, verbose_name='Type Id'),
        ),
    ]
