# Generated by Django 2.1.3 on 2019-03-30 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0032_order_items_order_item_type_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItems',
            new_name='Inventory_Items',
        ),
        migrations.RenameModel(
            old_name='ProductRequestItems',
            new_name='Product_Request_Items',
        ),
        migrations.RenameModel(
            old_name='ProductRequests',
            new_name='Product_Requests',
        ),
    ]
