# Generated by Django 2.1.3 on 2019-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0034_auto_20190330_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='inventory_order_purchase_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='Purchase Order No.'),
        ),
    ]
