# Generated by Django 2.1.3 on 2019-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0035_auto_20190330_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_from_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('supplier', 'Supplier'),
                                            ('product-request', 'Product Request'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_model_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('supplier', 'Supplier'),
                                            ('product-request', 'Product Request'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_to_type',
            field=models.CharField(choices=[('', '--select--'), ('system', 'System'), ('order', 'Order'),
                                            ('order-proposal', 'Order Proposal'), ('supplier', 'Supplier'),
                                            ('product-request', 'Product Request'), ('operator', 'Operator')],
                                   default='system', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product_request_items',
            name='product_request_item_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Stock Request Id'),
        ),
        migrations.AlterField(
            model_name='product_requests',
            name='product_request_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Stock Request Id'),
        ),
    ]
