# Generated by Django 2.1.3 on 2019-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0039_auto_20190331_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='attachment_type',
            field=models.CharField(
                choices=[('', '--select--'), ('none', 'None'), ('email', 'Email'), ('order', 'Order'),
                         ('order-email', 'Order Email'),
                         ('order-proposal-business-license', 'Order Proposal Business License'),
                         ('order-proposal-offer-letter', 'Order Proposal Offer Letter'),
                         ('order-proposal-quotation', 'Order Proposal Quotation'),
                         ('order-proposal-vat-registration', 'Order Proposal Vat Registration'),
                         ('order-proposal-other-document', 'Order Proposal Other Document'),
                         ('order-proposal-reference-document', 'Order Proposal Reference Document'),
                         ('order-purchase', 'Order Purchase'), ('order-invoice', 'Order Invoice'),
                         ('order-payment-voucher', 'Order Payment Voucher')], default='none', max_length=255,
                verbose_name='Type'),
        ),
    ]
