# Generated by Django 2.1.3 on 2019-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0042_auto_20190404_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='mel_results',
            name='mel_indicators_mel_indicator_code',
            field=models.CharField(default='', max_length=8, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='mel_activities',
            name='mel_activity_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Activity Id'),
        ),
        migrations.AlterField(
            model_name='mel_indicators',
            name='mel_indicator_code',
            field=models.CharField(max_length=8, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='mel_indicators',
            name='mel_indicator_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Indicator Id'),
        ),
        migrations.AlterField(
            model_name='mel_results',
            name='mel_result_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Intermediate Result Id'),
        ),
        migrations.AlterField(
            model_name='mel_sub_results',
            name='mel_sub_result_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Sub-intermediate Result Id'),
        ),
    ]
