# Generated by Django 2.1.3 on 2019-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0044_auto_20190404_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mel_results',
            name='mel_indicators_mel_indicator_code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
    ]
