# Generated by Django 2.1.3 on 2019-04-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20190405_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mel_activities',
            name='mel_activity_target_achieved',
        ),
        migrations.RemoveField(
            model_name='mel_activities',
            name='mel_activity_target_estimated',
        ),
    ]
