# Generated by Django 2.2 on 2019-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0046_auto_20190405_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mel_results',
            old_name='mel_indicator_ids',
            new_name='mel_result_indicator_ids',
        ),
        migrations.AlterField(
            model_name='mel_results',
            name='mel_result_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Component Id'),
        ),
        migrations.AlterField(
            model_name='mel_sub_results',
            name='mel_sub_result_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Indicator Level Id'),
        ),
    ]
