# Generated by Django 2.2 on 2019-04-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0047_auto_20190415_0746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mel_Sub_Results',
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_apr',
            field=models.IntegerField(default=0, verbose_name='Achieved APR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_aug',
            field=models.IntegerField(default=0, verbose_name='Achieved AUG'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_dec',
            field=models.IntegerField(default=0, verbose_name='Achieved DEC'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_feb',
            field=models.IntegerField(default=0, verbose_name='Achieved FEB'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_jan',
            field=models.IntegerField(default=0, verbose_name='Achieved JAN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_jul',
            field=models.IntegerField(default=0, verbose_name='Achieved JUL'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_jun',
            field=models.IntegerField(default=0, verbose_name='Achieved JUN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_mar',
            field=models.IntegerField(default=0, verbose_name='Achieved MAR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_may',
            field=models.IntegerField(default=0, verbose_name='Achieved MAY'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_nov',
            field=models.IntegerField(default=0, verbose_name='Achieved NOV'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_oct',
            field=models.IntegerField(default=0, verbose_name='Achieved OCT'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_achieved_sep',
            field=models.IntegerField(default=0, verbose_name='Achieved SEP'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_annual_target',
            field=models.TextField(blank=True, verbose_name='Annual Target'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_district',
            field=models.CharField(default='', max_length=255, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_managed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Managed By'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_managed_department',
            field=models.CharField(blank=True, max_length=255, verbose_name='Managed Department'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_managed_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Managed ID'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_managed_role',
            field=models.CharField(blank=True, max_length=255, verbose_name='Managed Role'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_apr',
            field=models.IntegerField(default=0, verbose_name='Planned APR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_aug',
            field=models.IntegerField(default=0, verbose_name='Planned AUG'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_dec',
            field=models.IntegerField(default=0, verbose_name='Planned DEC'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_feb',
            field=models.IntegerField(default=0, verbose_name='Planned FEB'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_jan',
            field=models.IntegerField(default=0, verbose_name='Planned JAN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_jul',
            field=models.IntegerField(default=0, verbose_name='Planned JUL'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_jun',
            field=models.IntegerField(default=0, verbose_name='Planned JUN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_mar',
            field=models.IntegerField(default=0, verbose_name='Planned MAR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_may',
            field=models.IntegerField(default=0, verbose_name='Planned MAY'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_nov',
            field=models.IntegerField(default=0, verbose_name='Planned NOV'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_oct',
            field=models.IntegerField(default=0, verbose_name='Planned OCT'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_planned_sep',
            field=models.IntegerField(default=0, verbose_name='Planned SEP'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_apr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status APR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_aug',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status AUG'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_dec',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status DEC'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_feb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status FEB'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_jan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status JAN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_jul',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status JUL'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_jun',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status JUN'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_mar',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status MAR'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_may',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status MAY'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_nov',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status NOV'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_oct',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status OCT'),
        ),
        migrations.AddField(
            model_name='mel_activities',
            name='mel_activity_status_sep',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status SEP'),
        ),
        migrations.AddField(
            model_name='mel_results',
            name='mel_result_domain_of_intervention',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domain of Intervention'),
        ),
        migrations.AddField(
            model_name='mel_results',
            name='mel_sub_result_details',
            field=models.TextField(default='', verbose_name='Indicator Level'),
        ),
        migrations.AlterField(
            model_name='mel_activities',
            name='mel_activity_details',
            field=models.TextField(verbose_name='Planned Activities'),
        ),
        migrations.AlterField(
            model_name='mel_indicators',
            name='mel_indicator_details',
            field=models.TextField(verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='mel_results',
            name='mel_result_details',
            field=models.TextField(verbose_name='Component'),
        ),
    ]
