from django.conf import settings


def global_settings(request):
    # return any necessary values
    return {
        # Project related
        'TEMPLATE_PATH_BACKEND': settings.TEMPLATE_PATH_BACKEND,
        # Project related
        'APP_CONSTANT_APP_NAME': settings.APP_CONSTANT_APP_NAME,
        'APP_CONSTANT_APP_SHORT_NAME': settings.APP_CONSTANT_APP_SHORT_NAME,
        'APP_CONSTANT_APP_NAME_NO_SPACE': settings.APP_CONSTANT_APP_NAME_NO_SPACE,
        'APP_CONSTANT_APP_PACKAGE_NAME': settings.APP_CONSTANT_APP_PACKAGE_NAME,
        'APP_CONSTANT_APP_VERSION_CODE': settings.APP_CONSTANT_APP_VERSION_CODE,
        'APP_CONSTANT_APP_VERSION_NAME': settings.APP_CONSTANT_APP_VERSION_NAME,
        'APP_CONSTANT_COMPANY_NAME': settings.APP_CONSTANT_COMPANY_NAME,
        'APP_CONSTANT_COMPANY_WEBSITE': settings.APP_CONSTANT_COMPANY_WEBSITE,
        'APP_CONSTANT_TECH_SUPPORT_EMAIL_ID': settings.APP_CONSTANT_TECH_SUPPORT_EMAIL_ID,
        'APP_CONSTANT_ADMIN_SUPPORT_EMAIL_ID': settings.APP_CONSTANT_ADMIN_SUPPORT_EMAIL_ID,
        # Datetime
        'TIME_ZONE': settings.TIME_ZONE,
        'APP_CONSTANT_DISPLAY_TIME_ZONE': settings.APP_CONSTANT_DISPLAY_TIME_ZONE,
        'APP_CONSTANT_DISPLAY_DATE_FORMAT': settings.APP_CONSTANT_DISPLAY_DATE_FORMAT,
        'APP_CONSTANT_DISPLAY_TIME_FORMAT': settings.APP_CONSTANT_DISPLAY_TIME_FORMAT,
        'APP_CONSTANT_DISPLAY_DATETIME_FORMAT': settings.APP_CONSTANT_DISPLAY_DATETIME_FORMAT,
        'APP_CONSTANT_INPUT_DATETIME_FORMAT': settings.APP_CONSTANT_INPUT_DATETIME_FORMAT,
        'APP_CONSTANT_INPUT_DATE_FORMAT': settings.APP_CONSTANT_INPUT_DATE_FORMAT,
        'APP_CONSTANT_INPUT_TIME_FORMAT': settings.APP_CONSTANT_INPUT_TIME_FORMAT,
        'APP_CONSTANT_DEFAULT_DATETIME': settings.APP_CONSTANT_DEFAULT_DATETIME,
        'APP_CONSTANT_DEFAULT_DATE': settings.APP_CONSTANT_DEFAULT_DATE,
        'APP_CONSTANT_DEFAULT_TIME': settings.APP_CONSTANT_DEFAULT_TIME,
        # Backend Sections
        'BACKEND_SECTION_DASHBOARD': settings.BACKEND_SECTION_DASHBOARD,
        'BACKEND_SECTION_SETTINGS': settings.BACKEND_SECTION_SETTINGS,
        'BACKEND_SECTION_OPERATORS': settings.BACKEND_SECTION_OPERATORS,
        'BACKEND_SECTION_PROFILE': settings.BACKEND_SECTION_PROFILE,
        'BACKEND_SECTION_CHANGE_PASSWORD': settings.BACKEND_SECTION_CHANGE_PASSWORD,
        'BACKEND_SECTION_HELP': settings.BACKEND_SECTION_HELP,
        'BACKEND_SECTION_ORDERS': settings.BACKEND_SECTION_ORDERS,
        # Operator Permissions
        'ACCESS_PERMISSION_DASHBOARD_VIEW': settings.ACCESS_PERMISSION_DASHBOARD_VIEW,
        'ACCESS_PERMISSION_SETTINGS_VIEW': settings.ACCESS_PERMISSION_SETTINGS_VIEW,
        'ACCESS_PERMISSION_OPERATOR_CREATE': settings.ACCESS_PERMISSION_OPERATOR_CREATE,
        'ACCESS_PERMISSION_OPERATOR_UPDATE': settings.ACCESS_PERMISSION_OPERATOR_UPDATE,
        'ACCESS_PERMISSION_OPERATOR_DELETE': settings.ACCESS_PERMISSION_OPERATOR_DELETE,
        'ACCESS_PERMISSION_OPERATOR_VIEW': settings.ACCESS_PERMISSION_OPERATOR_VIEW,
        'ACCESS_PERMISSION_LOG_CREATE': settings.ACCESS_PERMISSION_LOG_CREATE,
        'ACCESS_PERMISSION_LOG_UPDATE': settings.ACCESS_PERMISSION_LOG_UPDATE,
        'ACCESS_PERMISSION_LOG_DELETE': settings.ACCESS_PERMISSION_LOG_DELETE,
        'ACCESS_PERMISSION_LOG_VIEW': settings.ACCESS_PERMISSION_LOG_VIEW,
        'ACCESS_PERMISSION_ORDER_CREATE': settings.ACCESS_PERMISSION_ORDER_CREATE,
        'ACCESS_PERMISSION_ORDER_UPDATE': settings.ACCESS_PERMISSION_ORDER_UPDATE,
        'ACCESS_PERMISSION_ORDER_VIEW': settings.ACCESS_PERMISSION_ORDER_VIEW,
        'ACCESS_PERMISSION_ORDER_DELETE': settings.ACCESS_PERMISSION_ORDER_DELETE,

        # Model Titles
        'MODEL_OPERATORS_PLURAL_TITLE': settings.MODEL_OPERATORS_PLURAL_TITLE,
        'MODEL_OPERATORS_SINGULAR_TITLE': settings.MODEL_OPERATORS_SINGULAR_TITLE,
        'MODEL_BACKUPS_PLURAL_TITLE': settings.MODEL_BACKUPS_PLURAL_TITLE,
        'MODEL_BACKUPS_SINGULAR_TITLE': settings.MODEL_BACKUPS_SINGULAR_TITLE,

        # Colors
        'COLOR_PRIMARY': settings.COLOR_PRIMARY,
        'COLOR_PRIMARY_DARK': settings.COLOR_PRIMARY_DARK,
        'COLOR_PRIMARY_LIGHT': settings.COLOR_PRIMARY_LIGHT,
    }
